### ISSUE TITLE
Downloading Pexels.com Dataset

### ISSUE THREAD

**Issue by Adenialzz** [janpf/self-supervised-multi-task-aesthetic-pretraining#2]
Thank you for your great work and open source code. Can you provide the pre-training dataset of pexels you collected? Thanks a lot.

**Comment by janpf** [comment]
Hi,
I would really love to, but sharing the entire dataset of all preprocessed images is very prohibitive as they amount to 2.4 TB of data 🙈 
But no worries, you just need the unedited original images, from which you can generate all preprocessed files yourself.

I just noticed that pexels.com changed their website quite a bit since we downloaded the images ourselves. Luckily I still have the original URLs we used to download the images.

For acquiring the original, unedited images: download all images from https://github.com/janpf/self-supervised-multi-task-aesthetic-pretraining/blob/main/dataset/urls.txt as exemplarily layed out in https://github.com/janpf/self-supervised-multi-task-aesthetic-pretraining/blob/main/dataset/download_pexels.sh
Please implement some kind of ratelimiting to go easy on their servers.
This should result in 25-30GB of images (note that the `sed` command in the shellscript tells pexels to downsize the images for a smaller transfer size and less storage needed on your end)

After you are done downloading preprocess all images using the included imageeditor: https://github.com/janpf/self-supervised-multi-task-aesthetic-pretraining/blob/main/edit_image.py  according to the included `parameter_range` dict.
Exemplary usage at the end of the script.

**Comment by Adenialzz** [comment]
Thank you very much for your help.
