### ISSUE TITLE
error: Xmp schema version 3 in edit.xmp not supported

### ISSUE THREAD

**Issue by funykatebird** [janpf/self-supervised-multi-task-aesthetic-pretraining#6]
WARNING: either your user id or the effective user id are 0. are you running darktable as root?
[defaults] found a 64-bit system with 527873464 kb ram and 72 cores (0 atom based)
[defaults] setting very high quality defaults
error: Xmp schema version 3 in edit.xmp not supported
error: can't open xmp file edit.xmp

**Comment by ducanhnguyen-lab** [comment]
@funykatebird  @janpf  Do you solve this issue?

**Comment by ducanhnguyen-lab** [comment]
darktable:xmp_version="2" works, darktable:xmp_version="1" works too but the edited image is the same as the original image.

**Comment by janpf** [comment]
I'm sorry, but this issue contains next to no information for me to understand where and why this issue is happening.
We used the darktables version that was current at the time of publication.
I just found this line in a chat from back then:
https://download.opensuse.org/repositories/graphics:/darktable/Debian_10/amd64/darktable_3.2.1-1.1_amd64.deb
Hope this helps figuring out the version used, although the link seems to have gone stale :/

I can say though, that the XMP files are the original, untouched XMPs files we used.
